apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: togglemaster-flag
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flag-service
  ports:
    - port: 8002
      targetPort: 8002